### ISSUE TITLE
Installation on MacOS 10.14.6 fails on xgboost

### ISSUE THREAD

**Issue by fchiossi** [IBM/AIX360#70]
I followed these steps to install aix360 on MacOS 10.14.6
1) conda create --name aix360 python=3.6
2) conda activate aix360
3) git clone https://github.com/IBM/AIX360
4) cd AIX360/
5) pip install -e .

the command failed with the following error:

`(aix360) ~/AIX360 [master] $ pip install -e .
Obtaining file:///Users/fchiossi/AIX360
Collecting joblib>=0.11
  Using cached joblib-0.14.1-py2.py3-none-any.whl (294 kB)
Collecting scikit-learn>=0.21.2
  Using cached scikit_learn-0.22.1-cp36-cp36m-macosx_10_6_intel.whl (11.1 MB)
Collecting torch
  Using cached torch-1.4.0-cp36-none-macosx_10_9_x86_64.whl (81.1 MB)
Collecting torchvision
  Using cached torchvision-0.5.0-cp36-cp36m-macosx_10_9_x86_64.whl (438 kB)
Collecting cvxpy
  Using cached cvxpy-1.0.28-cp36-cp36m-macosx_10_9_x86_64.whl (745 kB)
Collecting cvxopt
  Using cached cvxopt-1.2.4-cp36-cp36m-macosx_10_9_x86_64.whl (3.1 MB)
Collecting Image
  Using cached image-1.5.28.tar.gz (15 kB)
Collecting keras
  Using cached Keras-2.3.1-py2.py3-none-any.whl (377 kB)
Collecting matplotlib
  Using cached matplotlib-3.1.3-cp36-cp36m-macosx_10_9_x86_64.whl (13.2 MB)
Collecting numpy
  Using cached numpy-1.18.1-cp36-cp36m-macosx_10_9_x86_64.whl (15.2 MB)
Collecting pandas
  Using cached pandas-1.0.1-cp36-cp36m-macosx_10_9_x86_64.whl (9.9 MB)
Collecting scipy>=0.17
  Using cached scipy-1.4.1-cp36-cp36m-macosx_10_6_intel.whl (28.5 MB)
Collecting tensorflow==1.14
  Using cached tensorflow-1.14.0-cp36-cp36m-macosx_10_11_x86_64.whl (105.8 MB)
Collecting xport
  Using cached xport-2.0.2-py2.py3-none-any.whl (14 kB)
Collecting scikit-image
  Using cached scikit_image-0.16.2-cp36-cp36m-macosx_10_6_intel.whl (30.4 MB)
Collecting requests
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting lime
  Using cached lime-0.1.1.37.tar.gz (275 kB)
Collecting shap
  Using cached shap-0.34.0.tar.gz (264 kB)
Collecting xgboost
  Using cached xgboost-1.0.1.tar.gz (820 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/fchiossi/opt/anaconda3/envs/aix360/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/j1/x8bvblx563n247csfz521xkr0000gn/T/pip-install-lrjswknu/xgboost/setup.py'"'"'; __file__='"'"'/private/var/folders/j1/x8bvblx563n247csfz521xkr0000gn/T/pip-install-lrjswknu/xgboost/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/j1/x8bvblx563n247csfz521xkr0000gn/T/pip-install-lrjswknu/xgboost/pip-egg-info
         cwd: /private/var/folders/j1/x8bvblx563n247csfz521xkr0000gn/T/pip-install-lrjswknu/xgboost/
    Complete output (27 lines):
    ++ pwd
    + oldpath=/private/var/folders/j1/x8bvblx563n247csfz521xkr0000gn/T/pip-install-lrjswknu/xgboost
    + cd ./xgboost/
    + mkdir -p build
    + cd build
    + cmake ..
    ./xgboost/build-python.sh: line 21: cmake: command not found
    + echo -----------------------------
    -----------------------------
    + echo 'Building multi-thread xgboost failed'
    Building multi-thread xgboost failed
    + echo 'Start to build single-thread xgboost'
    Start to build single-thread xgboost
    + cmake .. -DUSE_OPENMP=0
    ./xgboost/build-python.sh: line 27: cmake: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/j1/x8bvblx563n247csfz521xkr0000gn/T/pip-install-lrjswknu/xgboost/setup.py", line 42, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/j1/x8bvblx563n247csfz521xkr0000gn/T/pip-install-lrjswknu/xgboost/xgboost/libpath.py", line 50, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/j1/x8bvblx563n247csfz521xkr0000gn/T/pip-install-lrjswknu/xgboost/xgboost/libxgboost.dylib
    /private/var/folders/j1/x8bvblx563n247csfz521xkr0000gn/T/pip-install-lrjswknu/xgboost/xgboost/../../lib/libxgboost.dylib
    /private/var/folders/j1/x8bvblx563n247csfz521xkr0000gn/T/pip-install-lrjswknu/xgboost/xgboost/./lib/libxgboost.dylib
    /Users/fchiossi/opt/anaconda3/envs/aix360/xgboost/libxgboost.dylib
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

How can I fix it?

Thanks in advance

**Comment by fchiossi** [comment]
Fixed by running:
`brew update`
`brew install cmake`
